slogan: "An awesome blog about software development and network security."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  # - title: Tags
  #   url: tags
  #   intro: "All the tags."
  #   icon: "fa fa-tags"
  # - title: About
  #   url: about
  #   intro: "About me."
  #   icon: "fa fa-user"
  # - title: RSS
  #   url: atom.xml
  #   intro: "Subscribe me."
  #   icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/immortalt
    intro: "My Github account."
    icon: "fa fa-github"
  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
  - search
  - category
  - tagcloud
  - links
  - recent_comments
  - recent_posts

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: G-ZJT0X50ELX
piwik_analytics:
  enable: true
  siteid: 09a725f9-52e4-49d0-9691-6ccab4f70092
  username: immortalt

# search
#swiftype_key:

# built-in comment system
comment_js:
  type: "github"
  user: "immortal-blog"
  repo: "immortal-blog.github.io"
  client_id: "0926fba2ec35893ced81"
  client_secret: "f4eb7e8722e7eadb82df98401bbd86c4111a107c"
  count: 3
