categories: Categories
search: Search
tags: Tags
tagcloud: "Tag Cloud"
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
description: Description
read_more: "Read More"
links: Links
recent_comments: "Recent Comments"
no_comment: "No Comment"
go_to_comment: "Leave Comment"
no_issue: "No Issue"
